services:
  
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./Backend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - DOCKER=true
    command: npm run dev
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./web:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    restart: unless-stopped
