
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.prod
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - backend-network
    depends_on:
      - python-service


  python-service:
    build:
      context: ./python_server
      dockerfile: Dockerfile.python.prod
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
